services:
  minecraft:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: server-vanilla
    command: /entrypoint.sh
    ports:
      - 25565:25565
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./server:/server
    working_dir: /server